apiVersion: ENC[AES256_GCM,data:4LA=,iv:QcNuKX/LXpuaXB9Ndh8lWS4eUIp0VNTaPlgTnfVWPzU=,tag:kyx2wJd98Q5QSPHN8sjCcQ==,type:str]
kind: ENC[AES256_GCM,data:4tXWEOsr,iv:8KltwDKngvzKOnG4qjzk14FA89ey0WTJJKUZ/JE2u78=,tag:0DOn5wVBukU7aVQTmJihfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+Ktvrj9z9GboUvaOsS3+,iv:j88fTW3IGB5/qWh1NqAt2foQQFWQ25qcaS3wyrAHJOA=,tag:bABSB+JtVFI9W82ulzdJrg==,type:str]
    namespace: ENC[AES256_GCM,data:Kp6eW78J+A==,iv:wEICySLr6SHyg2KmMyP1D3RPpnG7JX/Lqzuf1ydYYbU=,tag:xtezd1bz8XZMa46X2oxOvA==,type:str]
type: ENC[AES256_GCM,data:hc/YPhjo,iv:fwh4WuU6w2caNIzb26PFPNcce5ArSBCzZUa0kd166Kw=,tag:7fHe96z6+sN1rbZwBatKbg==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:5j34aA==,iv:gyhEXzKU9rZJdOM+7aHYw3svNVk3kdrs3+QHIxWRrK8=,tag:9/iWrsKh2Bga2kJTt0lxHA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:OVYiIg==,iv:OGNsuLFJQzwVfy6qFzcSdm4of/svE5rWFJhV8D9TDBg=,tag:Oj26O/cCaxHljiC1uuNDCw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JV6r5TxVZxIIIwMR,iv:dc4TG6njz6JYax+ebvh9l7hkH7JYLJEFHOUKCJy/6mg=,tag:0JLMRhIY36mmjLR+tsE0qw==,type:str]
sops:
    age:
        - recipient: age1xenuqgfeetdrjj4egwgy8plfh5wvw0u7auckhkc4csryxsgp8p3sxrzg3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a3VMNUdUQVhjdTNEVGlC
            dTRNOEUrNGU2bVpJMElpRVd4aXVMdjBxejJJCk5XbWxGV3pZb1ZtQitSeFZnT0Ru
            RG9QT3Zza1lWNGs2VnhWV3ZYVURmUXcKLS0tIDRpaXZCVi81eEFpTE5jVUQzR0dY
            OW1JYmlRS09wUHpsc2lJV0JydDZ6a0UKWiZGrW55/b9+Y7EyScYNXpPuPGXx1ydY
            ttL08omQAtyWAMXLlYzw2/FrKHCbYaRKssh5H82QPwV9UL1ICHP+Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T23:09:10Z"
    mac: ENC[AES256_GCM,data:5hOi2rwS9rz4a5N0FMIK9KInG3eWCvnR+xKn8Q4JZCs5ZfcW2uz3WmG63ZFeXOatLeyyLNrAl8QmfOLAzlcLa8BoMxl/CgWRdu68fUe2OOxLeyChQzkqTEOweXFdRAnkPRBUZ4R10/I0fjv/cjQvURbXDSfAtPJVNV+DHO9BWp4=,iv:YIqTJ8xd3KYfg4t1Q8+zGGDdSSPmThiAA1Ik3R8y67o=,tag:JLaMu0O1XXZPInz2nhdaRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
